language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "uHXas/4dafbP6/UKBuW23V8vaAaRYOCaToeb8T0fo71CQ8vB4Pea5ML4mL7+fuG14W0XhL28/nFyMCrlfsiaO4ky1kC9tqoGP7P8SvMyaftUdd0IHW5f6DSB+u8Nwq2mg6yocew+Lm5GVFnZmwucjaiXy+w7hPpGe5rCsy2jBpIttjSaBAfUk/Fawr/akT38GI6mW7vrHR/2cxQLVJ2L+I9zoDpT7XM2B2fsuaB6SBAMHPihsnVFpBLa4oyyMjEi01fBV8LC/E3tRabyV/IUbfqYNH6uWJcBL0quIeK5ON5UY7naJ3ajw00kipAwmlCMb6JhkLIAzwePDYSzBMYFUk6doYqB7zXXpE1zQJ1BcADO0rwDbOcOy2G7sZeusokTape/kZLCUltA22Dh8uF1OdLGDezAAb358CmH04KyctqJdQgKN+kCMU5CJLUey8HS+3DkuKbrY6dCvQUsRZSQdc1dcAkl7veEVE67fOf8dZ6v96hF3tcl5XwncA6yCk4X7rUb41XVsTrcizy0KJAq+Pu+tQ8S/RlaWAYTc7tqXM7SAU3Yg1mmpXdF6XIRL+2YPZpfqsUYtKVZHR37RuX95Lcp07YapXVMRJTmKKCAA7lZb1j+ZDz+lgmjPM6iyWYe6REbuN4fI0NzWFQVe/7CnNpXbkwU/vPzwufnxHphHE0="
  - secure: "oC21/4F6Z3ELLSjHcvEqxQTxEAfyTOntx+iPp7znxQ51jFR/ByJRoQvfo2b1fUpN7oYZ62O8q2jcX6HPfUabKyOH638w9XCCKraf+po8pANYBTyIoJxX2Fw4Trr6KYkQHDHaXpPj/o7/wHRJ/18NN+W8AwDMtSeNUe6YSpgjXqKQk/EcRsnx/I06CRluT5jT48RXwJ7czYXg8W1zdJUeOyw70snHDvz3xn8qK01j/unwkqzLBf/wBps63y2hAdLYEYWO9/a3zDLLS8roZ84/BiizqP/s2I3fvQI10qNt9TtKriJSoErPPsKAB0NxcsoB+5IaociiUCGJH0axfWOBo3Dwy7ytekhEViDsjSOKJzApiV0wPJaXp5BiB0Ul6eXYCa6WpHbkjjhkx5OIfJnvW8uo5R56ITQq29NaVw2wUawJPuPHweC2c1tri+QGN7JVwzPnK/igqnftRiKJZwTFXcojGcUUZuGqm105MftsqTDDAmuESisWzAhwft3CGK9Pbo1fMT0MsXOvNO/C7ss5yPYfwfLIm0/U5OwC4+HJ9TzsCRBe7XirJrEH8pd4P9aQ9mkyQbavrgI6MLDn6lJRm0tpvu/OCwHt+f/28GnmrmZxvEUGnCaLSeGeArmXxnAoLT8Lj0MjwFzTEyNbC8K8l+1mt8ZYC/5xLqcsPt/Bk/o="
  - secure: "sEhwFwqoTaR1E93XFx8Ou5JpaeJHarjwYFxg92AuIZMvz6evOPyRPm6Mf8XPBVsvFd5aNqmq51ihv6m153QPvef0CZ1S/bcahaGZP8XnkiV/4G4KpZ+wQO5Z7bS+fL1Bblz5v7wORX27xJnGnJossu+19/HJ2lZFBX7Rjb+VuBdYFElpSvqxQBHHQuC9IOLpfoN003es2aaiogOdzEs7PCM1CT8UwlJqA+CSQRX5HAVR3GoYORgieUDZ/9D2PS6B/I7nfsQgQBdmu5yGSSjyZdC/bKBP+a2FkHLQcmJLYfeQD+iZaGGJ+kpjTw2zGejVzRw3K2W4DOcVIKzRr7ysWpY/JE33gQOkdebMsbif8viklOjXtNF6VpMsNyrrMAsbABMRRVRfoL1DFWzJQ1HAY1sVtu73378QMSDyv0IWgyjyLy7xhcIDPSkKccBxxwEbCwGcnE+cGk435aoCGb4oywvjDztXfulOTHdgZPAHf2YaDB+QpMjSQfrfywmjgXphvmYFbaLcNVwRIQPkbVGBT9ZQeUz4erUc0i4Qsp8hmE/CQ/shAapCODhKbutbMAq747WCY1zimvfu6i6qPyZMao78P3aNL9LXB1Ami6oL6JQVDHmCvG/YlgkoGRuolyqAbp9Fb7qZmpbQHwOtCdIJxk0/LwuWTWb0KCw+a+9HV38="
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_0ee33e9f2919_key -iv $encrypted_0ee33e9f2919_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
