language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: FiTOG3SKg3K9vz8XdeSKaXOmHV15eentDsXdZaweovshoYG4dkL/uwdsYU9jHTwa1zZUYI33Mk+MJ3jD1Llt5/bUN4ogtoT/ip5Omwl8nU8BtwS+6E07smUxSpsf9bxqQu8ljjHcqDzv6lCdilMUUmwg3+MYBTZUPqC2taq6f8iArRuVOxz5g3TcO5qcEk22GnHXkihribDkMJGb+FaFAKac8vVlpODE78gF6w5PwDng7TUUFydfWoI4m+AYpI/kRVFxO4u2ZNL/TGIUbTqXTpaLJd/1SIi3O49hnzD3UC3ERdPTbteFEYuPgdHhtpwc0T7rgos/arJzyV+ZparhHkVrlafkNlngC97zDAZVjrT96Sh+6g2idpn4UFB7DeVCM3G52MeRJhRLnES/9p4UC2qs7eN5x0PCJhg+uSn1rGSk6nPexBOLyBzUIrim9gOZG8YSYu3rjunohQrpxqnzJbomi7/UzQAo6bxbY4QoKw337kImIOdWLXnFWe4H4SeMtEVhDx4/P2Mn1R5A0JWrGd9swxqr8RpcdJlqXOb82JEooQjHunRRZquEZ4z1GyjSSq/AaCiysHm0yhp+ZtgARXpHSlc8EMg0Ye7DdHgNTJIfW2AhAMiH8deJOb9AGg/NlRR2kQ7ZAe3xPWrqOX+R67URp05RR3X5iFWcT8WWdO8=
  - secure: WenyH9CbT3iVKbGGUdBGj7Gufdi1GrEA5GCCX7pB2hP02D0vdu+H1+D0gwlUzAorqALfFamsfh0oajMF8WM/nSb39AkR4elfpbKMPJ9sR+P8UUARuoE+DH6/bCGNIBxix57w3P7FudCXLIQtZPv1nDB4F/pmXidOGl1UzqGch5MLuCJIKDIeu7zYFoon2W9MOYZZPo8bxDHp50PcWCDVew6FxqxSwtDCi/596Q7lKb1UQ/HqX3aAdiu8Cewil89bhz/tGcyV9kh5vtz8qXd7p284Ms7h8c+b5Wgxy2Dbu6I4NUzUy58uYMVvqAyjeC+SkDzddkFi7W+XlLCiLGJSaX4LsYw7HVeuKUXkpue4XZA7OQp6pHdNWfsJJMBtk5kCGou75ELPmUWNZ1g/GV4tOiICs5LnSjWn8lEFa7m7oU5Wf3FwgXD/DZld2vvq5uMoII6AjiKRDNnigXt6H7HYkYMUhbmgxuWktXtXT8Grc7F4z57bipsrfeH2TQWhzrh8pbLp86HBLSlk0Zn3cb4ONrUXebacjQNpavRkaEWGQqiJGVyimFjGEGVZOq+KJDse3xszy0ntwgPR3t8g3dBUqrmyCcV1mNlEdfcCI41PQdLuQLlSGHO6lP1pH60JEyH4LnIutS8NbKg9wTDEDlS+isrthatXUuDExcM+ZQDxNlA=
  - secure: lBbexgXrwhvft5D8tfoiSCv8RRCi6SEnOO2pv3tK1w+qWx4qYNWc21hg26koYlqPf5zmQ0gbGsjufWwk/Wo5kZaBxtK3eKh6jYwZqCRJhPce4CFsVrRMj/tj7rLQXwO6KGADXZisVF1zEEQsSIGHkBhfn2HhaXFhfMVbl4NT6Nn61xaqTUYcCcec7oaW7Nap/OeKBW8VRkINOtdLfRYN7n7wg/5j4aQMid22dIRCfCArxg1jMSZMUt8ZB1LIhcGygvMyRGFVK+rul9W674IGUQUOOSqBqO1n9CCkJoxD85khHP3DRm/zD9q79xgAU6YpB+SYxvLf9vcvioWgPaVJhrZ8ZOf10SDGKF5+zn1eumVSLHqt0Rqwk1SRjleVQWynAVl5pfJAy7JJ6g3rQD5b1UeaG+Gyi/UwZX4vgns7q7x/OUuJvLAZGosy2QWJLXae/HX2nVmaT6oFFWcIeGnSJDM1I8+CgTcoqvyDvsRT5YXI0voKZo50NvAWXybhzYrIxwGArwh+q5Mny57nBBbw9dF4U9BtvgJEG1h+beqmscOypjoWfWaynNdmFz81/stZzfsKeEx6Yt16tzt9vKUFkuAMlRUPt1hcc3T4bAdBkqlNWMUhnkbQJk+qC9+CHSTPnu5OT/3MXRJALGD5GDSV+OLZuj0SRYxU3d4Q/Y6bWIQ=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_0ee33e9f2919_key -iv $encrypted_0ee33e9f2919_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
